---
title: "gather/merge eQTL and DTE data"
#output: html_notebook
---

```{r}
library(arrow)
library(data.table)
library(BiocParallel)
library(qs)
library(SummarizedExperiment)
library(stringi)
```

```{r}
tgr <- qread('mdd_data/tgr.GRanges.n796449.qs')
tdt <- as.data.frame(mcols(tgr))
#names(tgr) <- tgr$transcript_id
setDT(tdt, keep.rownames = 'gtxid')
## select only columns we want to add as annotation
tdsel=tdt[, .(transcript_id, gtxid, gene_id, gene_name, numexons,
                              Length, reftx, class, refgene, njx)]
tdsel$njx <- gsub(',',';', tdsel$njx, fixed=T)

tdsel$xgene <- tdsel$gene_name
tdsel[xgene=='.', xgene:=refgene]
#setDT(tdt, key = 'transcript_id')

fsnps <- 'eqtl/mdd/MDD_risk_snps.txt'
riskdt <- fread(fsnps, header=F, data.table = F)
## load DE results as well:
rde <- load('mdd_data/DE_results.Rdata')
## DEtxlist, DEglist and DTEsum objects loaded
```


```{r}
#read parquet output of tensorqtl for chr 1
regions=c('Amygdala', 'sACC')
edts <- list() # eqtl data tables per region

fns <- list()
fnsde <- list()

tbls <- list()
tblsDE <- list() #DE FDR<0.05 tables
rebuildTables=F

for (region in regions) {
  fns[[region]] <- paste0('mdd_data/eQTL_DTE_integrated_',region, '.csv.gz') 
  fnsde[[region]] <- paste0('mdd_data/DTE_report_',region, '.csv.gz')
  if (!file.exists(fns[[region]]) | !file.exists(fnsde[[region]])) {
    rebuildTables=T
    break
  }
}

if (!rebuildTables) {
  message("load prepared tables")
  for (region in regions) {
    tbls[[region]] <- fread(fns[[region]])
    tblsDE[[region]] <- fread(fnsde[[region]])
  }
} else {
    for (region in regions) {
     feqtls=paste0('eqtl/mdd/tx_', region, '_gwnom_FDR05.qs')
     if (!file.exists(feqtls)) {
        pfiles <- list.files(path='eqtl/mdd/out_nominal', pattern=paste0('tx_',region,'_.+\\.parquet$'), 
                                                                          recursive = T, full.names = T)
        cat("   ", length(pfiles), "parquet files found for", region, "\n")
        stopifnot(length(pfiles)<=23)
        dlst <- bplapply(pfiles, function(f) {
           pdt <- read_parquet(f)
           setDT(pdt)
           pdt[, fdr:=p.adjust(pval_nominal, "fdr")]
           pdt <- na.omit(pdt, cols='pval_nominal')
           setorder(pdt, fdr)
           sigdt <- pdt[fdr<=0.05,]
           rm(pdt)
           return(sigdt)
         }, BPPARAM=MulticoreParam(16))
         edts[[region]] <- rbindlist(dlst)
         cat(" ..saving", feqtls, "\n")
         qsave(edts[[region]], file=feqtls)
        } else {
          cat(" ..loading", feqtls, "\n")
          edts[[region]] <- qread(feqtls)
        }
    }
}
```

```{r}
dtes <- list()
sig_eqtl <- list()
sig_dte <- list()
txqtl <- list() #min eQTL FDR per transcript, by region

if (rebuildTables) {
    for (region in regions) {
      cat("merging eQTL and DTE for", region, "\n")
      edts[[region]]$riskSNP <- F
      edts[[region]][variant_id %in% riskdt$V1, riskSNP := TRUE]
      setnames(edts[[region]], 'phenotype_id', 'transcript_id') 
      edts[[region]] <- edts[[region]][tdsel, on=.(transcript_id), nomatch = 0 ]
      setnames(edts[[region]], 'fdr', 'FDR')
      dte <- fread(paste0('mdd_old/DE_tables/byGrpCf.MDD_CTL..',region,'.topTable_all.csv.gz'))
      setnames(dte, 'tid', 'gtxid')
      dte$transcript_id <- sapply(strsplit(dte$gtxid, "|", fixed=T), '[', 2)
      tblsDE[[region]] <- dte[adj.P.Val<0.05]
      setnames(tblsDE[[region]], c('AveExpr', 'P.Value',  'adj.P.Val'), c('logAvgExpr', 'pval', 'FDR') )
      dtesel <- dte[, .(transcript_id, logFC, AveExpr, t, P.Value, adj.P.Val, B)]
      setnames(dtesel, c('logFC', 'AveExpr', 't', 'P.Value', 'adj.P.Val', 'B'), 
                       c('DE_logFC', 'DE_logAvgExpr', 'DE_t', 'DE_pval', 'DE_FDR', 'DE_B'))
      dtes[[region]] <- dtesel
      sig_dte[[region]] <- dtesel[DE_FDR<0.05]
      setkey(sig_dte[[region]], 'transcript_id')
      sig_eqtl[[region]] <- edts[[region]][FDR<0.05] # all should be FDR<0.05
      sig_eqtl[[region]][ , eqtl_id := paste0(transcript_id, '.', variant_id)]
      ## group eQTLs by transcripts, keep minimum
      txqtl[[region]] <- sig_eqtl[[region]][, .(eqtlFDR=min(FDR)), by='transcript_id']
      
      setkey(sig_eqtl[[region]], 'eqtl_id')
      #tbls[[region]] <- edts[[region]][dtesel, on=.(transcript_id)]
      tbls[[region]] <- merge(edts[[region]], dtesel, by='transcript_id', all.x=T )
      tbls[[region]][ , eqtl_id := paste0(transcript_id, '.', variant_id)]
      setkey(tbls[[region]], 'eqtl_id', physical = F)
    }
    
    
    for (rix in seq_along(regions)) {
      oix=3-rix # the other index
      cat("preparing final eQTL_DE table for", regions[rix], "\n")
      tbls[[rix]] <- merge(tbls[[rix]], sig_eqtl[[oix]][, .(eqtl_id, FDR)], by='eqtl_id', all.x=T)
      #FDR.x, FDR.y columns are created
      tbls[[rix]] <- merge(tbls[[rix]], sig_dte[[oix]][, .(transcript_id, DE_FDR)], by='transcript_id', all.x=T)
      
      setnames(tbls[[rix]], c('FDR.x', 'FDR.y', 'DE_FDR.x', 'DE_FDR.y'),
                              c('FDR',   'oFDR',  'DE_FDR',   'oDE_FDR'))
      tbls[[rix]][FDR<0.05 & oFDR<0.05, sig_EQTL:='both']
      tbls[[rix]][is.na(sig_EQTL) & FDR<0.05, sig_EQTL:=regions[[rix]]]
      tbls[[rix]][is.na(sig_EQTL) & oFDR<0.05, sig_EQTL:=regions[[oix]]]
      tbls[[rix]][is.na(sig_EQTL), sig_EQTL:='none'] #shouldn't be any!!
      
      tbls[[rix]][DE_FDR<0.05 & oDE_FDR<0.05, sig_DTE:='both']
      tbls[[rix]][is.na(sig_DTE) & DE_FDR<0.05, sig_DTE:=regions[[rix]]]
      tbls[[rix]][is.na(sig_DTE) & oDE_FDR<0.05, sig_DTE:=regions[[oix]]]
      tbls[[rix]][is.na(sig_DTE), sig_DTE:='none']
      tbls[[rix]][, `:=`(oFDR=NULL, oDE_FDR=NULL, eqtl_id=NULL, gtxid=NULL)]
      setorder(tbls[[rix]], FDR)
      setcolorder(tbls[[rix]], c('xgene','transcript_id','variant_id', 'riskSNP', 'sig_EQTL', 'sig_DTE'))
      #setcolorder(tbl[[rix]], ')
      tbls[[rix]]$refgene <- NULL
      cat(" saving eQTL_DE table: ", fn , "\n")
      fn=paste0('mdd_data/eQTL_DTE_integrated_',regions[rix], '.csv.gz')
      fwrite(tbls[[rix]], file=fn)
      ## DTE tables:
      cat("preparing final DTE table for", regions[rix], "\n")
      tblsDE[[rix]] <- merge(tblsDE[[rix]], txqtl[[rix]], by='transcript_id', all.x=T)  # min eqtlFDR for each tx 
      tblsDE[[rix]] <- merge(tblsDE[[rix]], txqtl[[oix]], by='transcript_id', all.x=T)  # min eqtlFDR in the other region
      
      tblsDE[[rix]] <- merge(tblsDE[[rix]], sig_dte[[oix]][, .(transcript_id, DE_FDR)], by='transcript_id', all.x=T)
      setnames(tblsDE[[rix]], c('eqtlFDR.x', 'eqtlFDR.y', 'DE_FDR', 'Symbol'),
                              c('eqtlFDR',   'oeqtlFDR',  'oFDR', 'gene_name'))
      tblsDE[[rix]][eqtlFDR<0.05 & oeqtlFDR<0.05, sig_EQTL:='both']
      tblsDE[[rix]][is.na(sig_EQTL) & eqtlFDR<0.05, sig_EQTL:=regions[[rix]]]
      tblsDE[[rix]][is.na(sig_EQTL) & oeqtlFDR<0.05, sig_EQTL:=regions[[oix]]]
      tblsDE[[rix]][is.na(sig_EQTL), sig_EQTL:='none'] #shouldn't be any!!
      
      tblsDE[[rix]][FDR<0.05 & oFDR<0.05, sig_DTE:='both']
      tblsDE[[rix]][is.na(sig_DTE) & FDR<0.05, sig_DTE:=regions[[rix]]]
      tblsDE[[rix]][is.na(sig_DTE) & oFDR<0.05, sig_DTE:=regions[[oix]]]
      tblsDE[[rix]][is.na(sig_DTE), sig_DTE:='none']
      
      tblsDE[[rix]][, `:=`(oFDR=NULL, oeqtlFDR=NULL, eqtlFDR=NULL, gtxid=NULL)]
      setorder(tblsDE[[rix]], FDR)
      
      tblsDE[[rix]]$xgene <- tblsDE[[rix]]$gene_name
      tblsDE[[rix]][xgene=='.', xgene:=refgene]
      setcolorder(tblsDE[[rix]], c('xgene','transcript_id', 'FDR', 'logFC', 'sig_DTE', 'sig_EQTL'))
      cat(" saving DE report table: ", fn , "\n")
      tblsDE[[rix]]$refgene <- NULL
      fn=paste0('mdd_data/DTE_report_',regions[rix], '.csv.gz')
      fwrite(tblsDE[[rix]], file=fn)
      cat("  ", regions[rix], " tables written.\n")
    }
}
```


```{r}
## get a union table across the two regions
ateq <- tbls[[1]][, .(a_numSNP=.N, a_sigEQTL=fifelse(any(sig_EQTL=='both'), 'both', 'Amygdala'),
                      a_riskSNP=any(riskSNP)), by='transcript_id']
steq <- tbls[[2]][, .(s_numSNP=.N, s_sigEQTL=fifelse(any(sig_EQTL=='both'), 'both', 'sACC'), 
                      s_riskSNP=any(riskSNP)),  by='transcript_id']
mteq <- merge(ateq, steq, by='transcript_id', all=T)
#ignore numSNP for now
mteq[, have_riskSNP:=s_riskSNP | a_riskSNP]
mteq$sig_EQTL <- 'both'
mteq[is.na(s_sigEQTL), sig_EQTL:='Amygdala']
mteq[is.na(a_sigEQTL), sig_EQTL:='sACC']

mteq <- mteq[, .(transcript_id, sig_EQTL, have_riskSNP)]

adte <- tblsDE[[1]][, .(transcript_id, sig_DTE, sig_EQTL)]
setnames(adte, c('sig_DTE', 'sig_EQTL'), c('a_sigDTE', 'a_sigEQTL'))
sdte <- tblsDE[[2]][, .(transcript_id, sig_DTE, sig_EQTL)]
setnames(sdte, c('sig_DTE', 'sig_EQTL'), c('s_sigDTE', 's_sigEQTL'))
mdte <- merge(adte, sdte, by='transcript_id', all=T)
mdte$d_sig_DTE <- 'both'
mdte[is.na(s_sigDTE), d_sig_DTE:='Amygdala']
mdte[is.na(a_sigDTE), d_sig_DTE:='sACC']
mdte[, d_sig_EQTL:= fifelse(is.na(s_sigEQTL), a_sigEQTL, s_sigEQTL)]

mdte[, c('a_sigDTE', 'a_sigEQTL', 's_sigDTE', 's_sigEQTL')] <- NULL

## union of mdte and mteq

mrgtable <- merge(mdte, mteq, by='transcript_id', all=T)

mrgtable[, sig_DTE:=fifelse(is.na(d_sig_DTE), 'none', d_sig_DTE)]

mrgtable[, c('d_sig_DTE','d_sig_EQTL')] <- NULL
setcolorder(mrgtable, c('transcript_id','sig_DTE','sig_EQTL', 'have_riskSNP'))
mrgtable[is.na(sig_EQTL), sig_EQTL:='none']
mrgtable[is.na(have_riskSNP), have_riskSNP:=F]
#mrgtable$sig_DTE=sub('Amygdala', 'amyg', mrgtable$sig_DTE)
#mrgtable$sig_DTE=sub('sACC', 'sacc', mrgtable$sig_DTE)
# join with transfrag info table
mrgtd <- merge(mrgtable, tdsel, by='transcript_id')
mrgtd$gloc <- paste0(seqnames(tgr[mrgtd$gtxid]),':', ranges(tgr[mrgtd$gtxid]), strand(tgr[mrgtd$gtxid]))
setcolorder(mrgtd, c('transcript_id', 'xgene', 'gloc', 'sig_DTE', 'sig_EQTL', 'have_riskSNP'))


mrgtd$gtxid <- NULL
mrgtd$refgene <- NULL

fwrite(mrgtd, file='mdd_data/MDD_eQTL_DE_transfrags.summary_table.csv')
```

